### ISSUE TITLE
cPanel CA Bundle

### ISSUE THREAD

**Issue by ostap-mykhaylyak** [afosto/yaac#24]
Hello,
it seems that the CA bunlde is missing:

```
if ($client->isReady($order))
                {
                    $certificate = $client->getCertificate($order);
        
                    echo '<pre>' . $certificate->getCertificate(false) . '</pre>';
                    echo '<pre>' . $certificate->getPrivateKey() . '</pre>';
                    echo '<pre>' . $certificate->getIntermediate() . '</pre>';
                }

```

> Certificate verification failed! The system did not find the root certificate that corresponds to the supplied Certificate Authority Bundle’s intermediate certificate. Please supply a full Certificate Authority Bundle with the root certificate included.

**Comment by bakkerpeter** [comment]
Hi Ostap,

I'm not sure what you are asking for (since you only pasted an error
message) but I assume it's about getting a root certificate.

You can find the root here:
https://letsencrypt.org/certificates/

There is no way to get the root certs from the api or get notified about
changes without writing additional code, which is out of scope for this
package.

https://community.letsencrypt.org/t/api-to-stay-notified-of-root-cert-changes/75196/13

Regards

Op ma 27 jul. 2020 06:25 schreef Ostap <notifications@github.com>:

**Comment by bakkerpeter** [comment]
I have limited experience with cpanel, however in most web servers a intermediate cert should be sufficient (nginx fi). 
I'm closing the issue for now, if you have any questions let me know, but please provide some more insight into what you are asking.
